import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { TRPCReactProvider } from "~/trpc/react";
import { TopNav } from "./_components/topnav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Fallout 4 Random Start Me Up",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiasedfont-sans min-h-screen bg-background font-sans ${inter.variable}`}
        >
          <TopNav />
          <main className="overflow-y-scroll">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
